//! Stage S5 (Deploy) — deployment configuration + feature-flag generation
//! (spec §6.2, the *Stage S5* migration task).
//!
//! Generates the artifacts a migration needs to ship: a `helix-deploy.toml`
//! descriptor (target platforms, version) and a Rust feature-flag module the
//! generated guest can toggle at runtime. Both are emitted as plain text/TOML
//! so they are trivially diffable and testable without a deploy backend.

/// A target platform a migrated app can be built for.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TargetPlatform {
    LinuxX86_64,
    MacOS,
    Windows,
    Wasm32,
    Android,
    Ios,
}

impl TargetPlatform {
    /// The `cargo` target triple for this platform.
    pub fn triple(self) -> &'static str {
        match self {
            TargetPlatform::LinuxX86_64 => "x86_64-unknown-linux-gnu",
            TargetPlatform::MacOS => "aarch64-apple-darwin",
            TargetPlatform::Windows => "x86_64-pc-windows-msvc",
            TargetPlatform::Wasm32 => "wasm32-unknown-unknown",
            TargetPlatform::Android => "aarch64-linux-android",
            TargetPlatform::Ios => "aarch64-apple-ios",
        }
    }

    /// The `helix-deploy.toml` platform identifier.
    pub fn id(self) -> &'static str {
        match self {
            TargetPlatform::LinuxX86_64 => "linux-x86_64",
            TargetPlatform::MacOS => "macos",
            TargetPlatform::Windows => "windows",
            TargetPlatform::Wasm32 => "wasm32",
            TargetPlatform::Android => "android",
            TargetPlatform::Ios => "ios",
        }
    }
}

/// A deployment descriptor for a migrated application.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeployConfig {
    pub app_name: String,
    pub version: String,
    pub targets: Vec<TargetPlatform>,
}

/// Generate a `helix-deploy.toml` document for `cfg`.
///
/// Emits a `[package]` table plus one `[[target]]` entry per requested
/// platform, each carrying its cargo triple, so a CI build matrix can be
/// generated mechanically from the descriptor.
pub fn generate_deploy_config(cfg: &DeployConfig) -> String {
    // No targets selected → no deploy descriptor (Stage S5 skip).
    if cfg.targets.is_empty() {
        return String::new();
    }
    let mut s = String::new();
    s.push_str("# Generated by Helix migration Stage S5 (Deploy)\n");
    s.push_str("[package]\n");
    s.push_str(&format!("name = \"{}\"\n", cfg.app_name));
    s.push_str(&format!("version = \"{}\"\n", cfg.version));
    s.push('\n');
    for t in &cfg.targets {
        s.push_str("[[target]]\n");
        s.push_str(&format!("platform = \"{}\"\n", t.id()));
        s.push_str(&format!("triple = \"{}\"\n", t.triple()));
        s.push('\n');
    }
    s
}

/// A single deploy-time feature flag.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FeatureFlag {
    pub name: String,
    pub enabled: bool,
    pub description: String,
}

fn rust_ident(name: &str) -> String {
    let mut out = String::new();
    for c in name.chars() {
        if c.is_alphanumeric() || c == '_' {
            out.push(c);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        out.push('_');
    }
    out
}

/// Generate a Rust feature-flag module from `flags`.
///
/// Emits one `pub const <NAME>_ENABLED: bool` per flag plus an
/// `is_enabled(name)` lookup, giving the generated guest a uniform runtime
/// toggle API. Flag names are sanitized into valid Rust identifiers.
pub fn generate_feature_flags(flags: &[FeatureFlag]) -> String {
    let mut s = String::new();
    s.push_str("// Generated by Helix migration Stage S5 (Deploy) — feature flags\n");
    s.push_str("pub mod features {\n");
    for f in flags {
        let id = rust_ident(&f.name);
        s.push_str(&format!(
            "    /// {}\n    pub const {}_ENABLED: bool = {};\n",
            f.description,
            id.to_uppercase(),
            if f.enabled { "true" } else { "false" }
        ));
    }
    s.push_str("\n    /// Runtime lookup of a feature flag by its sanitized name.\n");
    s.push_str("    pub fn is_enabled(name: &str) -> bool {\n");
    s.push_str("        match name {\n");
    for f in flags {
        let id = rust_ident(&f.name);
        s.push_str(&format!(
            "            \"{}\" => {}_ENABLED,\n",
            id,
            id.to_uppercase()
        ));
    }
    s.push_str("            _ => false,\n");
    s.push_str("        }\n");
    s.push_str("    }\n");
    s.push_str("}\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn deploy_config_lists_targets_with_triples() {
        let cfg = DeployConfig {
            app_name: "notes".into(),
            version: "0.2.0".into(),
            targets: vec![TargetPlatform::LinuxX86_64, TargetPlatform::Wasm32],
        };
        let doc = generate_deploy_config(&cfg);
        assert!(doc.contains("name = \"notes\""));
        assert!(doc.contains("version = \"0.2.0\""));
        assert!(doc.contains("platform = \"linux-x86_64\""));
        assert!(doc.contains("triple = \"x86_64-unknown-linux-gnu\""));
        assert!(doc.contains("platform = \"wasm32\""));
        assert!(doc.contains("triple = \"wasm32-unknown-unknown\""));
        // Exactly two target entries.
        assert_eq!(doc.matches("[[target]]").count(), 2);
    }

    #[test]
    fn feature_flags_emit_constants_and_lookup() {
        let flags = vec![
            FeatureFlag {
                name: "beta-ui".into(),
                enabled: true,
                description: "New dashboard UI".into(),
            },
            FeatureFlag {
                name: "experimental-sync".into(),
                enabled: false,
                description: "Background sync".into(),
            },
        ];
        let src = generate_feature_flags(&flags);
        assert!(src.contains("pub const BETA_UI_ENABLED: bool = true;"));
        assert!(src.contains("pub const EXPERIMENTAL_SYNC_ENABLED: bool = false;"));
        assert!(src.contains("pub fn is_enabled(name: &str) -> bool"));
        assert!(src.contains("\"beta_ui\" => BETA_UI_ENABLED,"));
        assert!(src.contains("\"experimental_sync\" => EXPERIMENTAL_SYNC_ENABLED,"));
    }
}
