//! TPT Spark — local on-device code generation (spec §6.2, the
//! *Local Inference* row: "TPT Spark — On-device code generation").
//!
//! Spark is the generator. Given the transpiled guest from Stage S2 plus the
//! Stage S4 optimization suggestions and Stage S5 deploy artifacts produced by
//! TPT Eve (`eve`), it emits a complete, componentizable Helix guest crate:
//! a `Cargo.toml`, the generated `lib.rs` (WIT bindings + DOM ops + inferred
//! types + feature flags), and the `helix-guest` WIT `world`.
//!
//! The real TPT Spark service would own final code synthesis; this offline
//! implementation folds the already-computed pipeline artifacts into shippable
//! source so the migration can be built (`cargo build --target
//! wasm32-unknown-unknown`) and componentized without an external LLM.

use crate::deploy::TargetPlatform;
use crate::optimize::Suggestion;
use crate::transpile::TranspiledSite;

/// A fully generated, componentizable Helix guest guest.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GuestCrate {
    /// Crate name (from the migration plan).
    pub name: String,
    /// `Cargo.toml` contents.
    pub cargo_toml: String,
    /// `src/lib.rs` contents.
    pub lib_rs: String,
    /// `helix-guest.wit` world contents.
    pub world_wit: String,
}

fn rust_ident(name: &str) -> String {
    let mut out = String::new();
    for c in name.chars() {
        if c.is_alphanumeric() || c == '_' {
            out.push(c);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        out.push('_');
    }
    out
}

fn render_cargo_toml(name: &str, version: &str, targets: &[TargetPlatform]) -> String {
    let mut s = String::new();
    s.push_str("# Generated by Helix migration (TPT Spark stage)\n");
    s.push_str("[package]\n");
    s.push_str(&format!("name = \"{name}\"\n"));
    s.push_str(&format!("version = \"{version}\"\n"));
    s.push_str("edition = \"2024\"\n");
    s.push_str("license.workspace = true\n");
    s.push_str("publish = false\n\n");
    s.push_str("[lib]\n");
    s.push_str("crate-type = [\"cdylib\"]\n\n");
    s.push_str("[dependencies]\n");
    s.push_str("wit-bindgen = { version = \"0.59\", features = [\"macros\", \"realloc\"] }\n");
    if !targets.is_empty() {
        s.push('\n');
        s.push_str("# Deploy targets (from helix-deploy.toml):\n");
        for t in targets {
            s.push_str(&format!("#   {} -> {}\n", t.id(), t.triple()));
        }
    }
    s
}

fn render_optimization_notes(suggestions: &[Suggestion]) -> String {
    if suggestions.is_empty() {
        return String::new();
    }
    let mut s = String::new();
    s.push_str("\n// ── Stage S4 optimization suggestions ─────────────────────────────\n");
    for sug in suggestions {
        // Escape any `*/` that would close the block comment.
        let msg = sug.message.replace("*/", "* /");
        s.push_str(&format!("// [{}] {msg}\n", kind_label(sug)));
    }
    s.push_str("// ──────────────────────────────────────────────────────────────\n");
    s
}

fn kind_label(sug: &Suggestion) -> &'static str {
    match sug.category {
        crate::optimize::SuggestionKind::DeadCode => "dead-code",
        crate::optimize::SuggestionKind::StructPacking => "struct-packing",
        crate::optimize::SuggestionKind::LoopParallel => "loop-parallel",
    }
}

/// Generate a complete Helix guest crate from the pipeline artifacts.
///
/// * `site` — the Stage S2 transpiled guest (DOM ops + WIT world).
/// * `suggestions` — Stage S4 optimization notes, appended as comments.
/// * `feature_flags_src` — the Stage S5 `features` module source.
/// * `js` — optional JS/TS source; when present, Stage S2 type inference
///   (`type_infer`) runs and the inferred `types` module is embedded.
/// * `targets` — deploy targets, recorded in `Cargo.toml` comments.
pub fn generate_guest_crate(
    app_name: &str,
    version: &str,
    site: &TranspiledSite,
    suggestions: &[Suggestion],
    feature_flags_src: &str,
    js: Option<&str>,
    targets: &[TargetPlatform],
) -> GuestCrate {
    let name = rust_ident(app_name);
    let cargo_toml = render_cargo_toml(&name, version, targets);

    let mut lib_rs = String::new();
    lib_rs.push_str(&format!(
        "//! Helix guest crate `{name}` — generated by TPT Spark.\n//!\n\
         //! Built from the migrated DOM operations; componentize against the\n\
         //! `helix-guest` world and run on the Helix Runtime.\n\n"
    ));
    lib_rs.push_str(&site.rust_source);
    lib_rs.push('\n');
    lib_rs.push_str(&render_optimization_notes(suggestions));

    if let Some(js) = js {
        let bindings = crate::type_infer::infer_types(js);
        if !bindings.is_empty() {
            lib_rs.push_str("\n// Inferred types (Stage S2 type inference, custom backend)\n");
            lib_rs.push_str(&crate::type_infer::generate_rust_type_decls(&bindings));
        }
    }

    // Stage S5 feature flags become a `features` module in the guest.
    lib_rs.push('\n');
    lib_rs.push_str(feature_flags_src);

    GuestCrate {
        name,
        cargo_toml,
        lib_rs,
        world_wit: site.wit_world.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::deploy::TargetPlatform;
    use crate::transpile::{DomOp, TranspiledSite};

    fn sample_site() -> TranspiledSite {
        TranspiledSite {
            ops: vec![
                DomOp::Create {
                    var: "el0".into(),
                    tag: "div".into(),
                },
                DomOp::Text {
                    var: "el0".into(),
                    text: "hi".into(),
                },
            ],
            rust_source:
                "wit_bindgen::generate!({ world: \"helix-guest\", path: \"../helix-wit/wit\" });\n\n\
                 #[unsafe(no_mangle)]\n\
                 pub extern \"C\" fn run() {\n    use helix::runtime::dom;\n    let el0 = dom::create_element(&\"div\");\n    dom::set_text(el0, &\"hi\");\n}\n"
                    .into(),
            wit_world: "world helix-guest {\n    import dom;\n    export run: func();\n}\n".into(),
            crud: Default::default(),
            dataviz: Default::default(),
            media: Default::default(),
            realtime: Default::default(),
            spa: Default::default(),
        }
    }

    #[test]
    fn generates_well_formed_crate() {
        let site = sample_site();
        let flags = "pub mod features {\n    pub const HELIX_RUNTIME_ENABLED: bool = true;\n}\n";
        let guest = generate_guest_crate(
            "my-app",
            "0.2.0",
            &site,
            &[],
            flags,
            None,
            &[TargetPlatform::Wasm32],
        );
        assert_eq!(guest.name, "my_app");
        assert!(guest.cargo_toml.contains("name = \"my_app\""));
        assert!(guest.cargo_toml.contains("version = \"0.2.0\""));
        assert!(guest.cargo_toml.contains("wasm32-unknown-unknown"));
        assert!(guest.lib_rs.contains("pub extern \"C\" fn run()"));
        assert!(guest.lib_rs.contains("dom::set_text(el0, &\"hi\")"));
        assert!(guest.lib_rs.contains("pub mod features"));
        assert!(guest.world_wit.contains("export run: func()"));
    }

    #[test]
    fn embeds_inferred_types_and_notes() {
        let site = sample_site();
        let sug = vec![crate::optimize::Suggestion {
            category: crate::optimize::SuggestionKind::LoopParallel,
            message: "parallelize loop".into(),
            location: Some("line 3".into()),
        }];
        let guest = generate_guest_crate(
            "app",
            "1.0.0",
            &site,
            &sug,
            "",
            Some("const name = \"x\"; let n = 1;"),
            &[],
        );
        assert!(guest.lib_rs.contains("Stage S4 optimization suggestions"));
        assert!(guest.lib_rs.contains("[loop-parallel]"));
        assert!(guest.lib_rs.contains("pub mod inferred"));
        assert!(guest.lib_rs.contains("pub type name_t = String;"));
    }

    #[test]
    fn sanitized_name_handles_special_chars() {
        assert_eq!(rust_ident("my-app v2!"), "my_app_v2_");
        assert_eq!(rust_ident(""), "_");
    }
}
